apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: fuse-console
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: integration
    server: https://kubernetes.default.svc
  project: demo
  source:
    path: multiple-operators/fuse-console
    repoURL: https://github.com/gnunn1/operator-example
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
