apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: instance
  namespace: openshift-gitops
spec:
  destination:
    namespace: api-designer
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-app/instance
    repoURL: https://github.com/gnunn1/operator-example
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
