apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fuse-apicurito
spec:
  channel: fuse-apicurito-7.12.x
  installPlanApproval: Automatic
  name: fuse-apicurito
  source: redhat-operators
  sourceNamespace: openshift-marketplace
