apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-designer
  namespace: openshift-gitops
spec:
  destination:
    namespace: api-designer
    server: https://kubernetes.default.svc
  project: default
  source:
    path: all-in-one/manifests
    repoURL: https://github.com/gnunn1/operator-example
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
