apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: api-designer
    server: https://kubernetes.default.svc
  project: demo
  source:
    path: 3-app-of-app/operator
    repoURL: https://github.com/gnunn1/operator-example
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
