apiVersion: batch/v1
kind: Job
metadata:
  name: delete-csv-hook
  namespace: integration
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          env:
          - name: CSV_SELECTOR
            value: operators.coreos.com/fuse-apicurito.integration
          command:
          - /bin/bash
          - -c
          - |
            oc delete csv -l ${CSV_SELECTOR}
          name: delete-csv
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: delete-csv-hook
      serviceAccountName: delete-csv-hook
