apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-csv-hook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-csv-hook
rules:
  - apiGroups:
      - "operators.coreos.com"
    resources:
      - clusterserviceversion
    verbs:
      - delete
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-csv-hook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: delete-csv-hook
subjects:
  - kind: ServiceAccount
    name: delete-csv-hook
