apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-csv-hook
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-csv-hook
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
rules:
  - apiGroups:
      - "operators.coreos.com"
    resources:
      - clusterserviceversion
    verbs:
      - delete
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-csv-hook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: delete-csv-hook
subjects:
  - kind: ServiceAccount
    name: delete-csv-hook
