apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fuse-console
spec:
  channel: 7.12.x
  installPlanApproval: Automatic
  name: fuse-console
  source: redhat-operators
  sourceNamespace: openshift-marketplace
