apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 3-app-of-app/apps
    repoURL: https://github.com/gnunn1/operator-example
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
